// ============================================================
// PRODUCT DATA (compartido por index.html y producto.html)
// ============================================================
window.products = [
  {
    id: 1,
    brand: 'Lattafa',
    name: 'Oud for Glory',
    category: 'Árabe',
    catClass: 'bg-arabe',
    price: 49.99,
    image: 'Oud for Glory.avif',
    gallery: ['Oud for Glory.avif', 'caja oud for glory.png'],
    family: 'Ámbar Especiado',
    size: '100 ml',
    intensity: 'Alta',
    duration: '8+ horas',
    top: ['Azafrán', 'Canela', 'Bergamota'],
    heart: ['Rosa', 'Cedro', 'Pachulí'],
    base: ['Oud', 'Ámbar', 'Sándalo', 'Almizcle'],
    description: 'Un oud dramático y envolvente que abre con especias cálidas y azafrán para desembocar en un corazón amaderado. Su estela profunda de oud y ámbar lo convierte en la elección perfecta para quienes buscan presencia y magnetismo inolvidable. Ideal para noches y climas fríos.'
  },
  {
    id: 2,
    brand: 'Amouage',
    name: 'Interlude Black Iris',
    category: 'Nicho',
    catClass: 'bg-nicho',
    price: 195.00,
    image: 'Interlude Black Iris.avif',
    family: 'Amaderado Aromático',
    size: '100 ml',
    intensity: 'Intensa',
    duration: '10+ horas',
    top: ['Lavanda', 'Ajenjo', 'Cítricos'],
    heart: ['Iris', 'Tabaco', 'Agarwood'],
    base: ['Ámbar', 'Cuero', 'Vainilla'],
    description: 'La versión más oscura y elegante del icónico Interlude. El iris aterciopelado se entrelaza con tabaco y agarwood para crear un aroma magnético y sofisticado, con una estela larga e imponente imposible de ignorar. Perfecto para veladas especiales y quienes buscan dejar huella.'
  },
  {
    id: 3,
    brand: 'Tom Ford',
    name: 'Oud Wood',
    category: 'Diseñador',
    catClass: 'bg-disenador',
    price: 245.00,
    image: 'Oud Wood.avif',
    family: 'Amaderado Oriental',
    size: '100 ml',
    intensity: 'Media',
    duration: '8+ horas',
    top: ['Rosa', 'Cardamomo', 'Madera de Gaiac'],
    heart: ['Vetiver', 'Pachulí', 'Sándalo'],
    base: ['Oud', 'Ámbar', 'Vainilla', 'Sakura'],
    description: 'Un oud suave y refinado que redefine lo amaderado. Siempre sutil, sensual y pulcro, este clásico moderno combina la calidez del sándalo con un toque de vainilla para un acabado elegante, perfecto para el día a día en cualquier temporada.'
  },
  {
    id: 4,
    brand: 'Maison Alhambra',
    name: 'Tobacco Touch',
    category: 'Árabe',
    catClass: 'bg-arabe',
    price: 29.99,
    image: 'Tobacco Touch.avif',
    family: 'Ámbar Dulce',
    size: '100 ml',
    intensity: 'Alta',
    duration: '8+ horas',
    top: ['Cedro', 'Vainilla', 'Miel'],
    heart: ['Tabaco', 'Especias', 'Ámbar'],
    base: ['Tabaco', 'Cacao', 'Haba Tonka'],
    description: 'Un tabaco dulce y acogedor que envuelve como una manta cálida. La miel y la vainilla suavizan el tabaco especiado, dejando una estela dulce, gourmand y seductora con una excelente proyección.'
  },
  {
    id: 5,
    brand: 'Creed',
    name: 'Aventus',
    category: 'Diseñador',
    catClass: 'bg-disenador',
    price: 335.00,
    image: 'Creed Aventus.avif',
    family: 'Frutiado Amaderado',
    size: '100 ml',
    intensity: 'Media-Alta',
    duration: '10+ horas',
    top: ['Piña', 'Manzana', 'Bergamota', 'Grosella Negra'],
    heart: ['Abedul', 'Pachulí', 'Jazmín', 'Rosas'],
    base: ['Almizcle', 'Ámbar', 'Vainilla', 'Enebro'],
    description: 'Un ícono moderno de la perfumería. La jugosa piña y la bergamota dan paso a un corazón de abedul y pachulí con una base ambarada. Su estela imponente y su mezcla fresca-amaderada lo convierten en un clásico de éxito inconfundible.'
  },
  {
    id: 6,
    brand: 'Byredo',
    name: 'Gypsy Water',
    category: 'Nicho',
    catClass: 'bg-nicho',
    price: 220.00,
    image: 'Gypsy watter.avif',
    family: 'Bosque Aromático',
    size: '100 ml',
    intensity: 'Suave',
    duration: '4-6 horas',
    top: ['Bergamota', 'Limón', 'Pimienta'],
    heart: ['Incienso', 'Pino', 'Ámbar'],
    base: ['Vainilla', 'Sándalo', 'Almizcle'],
    description: 'Un aroma campestre inspirado en la vida nómada: cítricos frescos que abren hacia un corazón de incienso y pino, y una base cremosa de vainilla y sándalo. Íntimo, limpio y profundamente natural.'
  },
  {
    id: 7,
    brand: 'Rasasi',
    name: 'La Yuqawam',
    category: 'Árabe',
    catClass: 'bg-arabe',
    price: 59.99,
    image: 'La Yuqawam.avif',
    family: 'Cuero',
    size: '80 ml',
    intensity: 'Alta',
    duration: '10+ horas',
    top: ['Frambuesa', 'Azafrán', 'Romero'],
    heart: ['Cuero', 'Especias', 'Iris'],
    base: ['Ámbar', 'Almizcle', 'Vetiver'],
    description: 'Un cuero especiado de carácter dominante, dulce y oscuro a la vez, que recuerda al lujo de la perfumería de autor. Una firma intensa con excelente fijación, pensada para quienes buscan carácter y presencia.'
  },
  {
    id: 8,
    brand: 'Kilian',
    name: 'Angels Share',
    category: 'Nicho',
    catClass: 'bg-nicho',
    price: 275.00,
    image: 'Angels Share.avif',
    family: 'Coñac Gourmet',
    size: '50 ml',
    intensity: 'Media-Alta',
    duration: '8-10 horas',
    top: ['Coñac', 'Canela', 'Pimienta'],
    heart: ['Roble', 'Ciruela', 'Rosa'],
    base: ['Vainilla', 'Sándalo', 'Ámbar', 'Cedro'],
    description: 'Un homenaje al coñac añejado y al calor de una destilería. Notas alcohólicas de coñac se abren hacia una vainilla cremosa y especias dulces, creando un aroma cálido, gourmet y elegante con una estela memorable.'
  }
];